modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayTest="IGNORE_ALL_VERSION"
authors="Reiasu"
description='''
ReiParticlesAPI runtime for Forge 1.20.x.
Includes animation, emitter, display and test lifecycle services used by ReiParticleSkill.
'''

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${loader_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
